### ISSUE TITLE
When user accept cookies, store a cookie

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#106]
Related to #32 

- [x] If JS enabled, and after user clicks "Accept" on the cookie dialog, store a cookie `cookieAccepted` for 1 year.
- [x] If `cookieAccepted` found (true), then don't display the cookie dialog.

**Comment by lorezyra** [comment]
I see you added two new functions (`setWithExpiry` & `getWithExpiry`) based on `localStorage`. 
https://github.com/lorezyra/Richie2.com/blob/3ba4cd81fe43fa89f2f920e09de78f4e5e72bef6/assets/js/main.dev.js#L429-L461

Why are you using `localStorage` instead of cookies?

**Comment by Asem-prg** [comment]
There's no special reason in why using cookies, but I liked to do some thing new with `localStorage`.

I will change to use cookies.

**Comment by lorezyra** [comment]
Playing with ideas is cool. However, in this case, I actually want a cookie where the content is transmitted to the server. This enables me to see that every visitor actually accepted my cookie policy. "LocalStorage," as the name implies, never leaves the local user's device. It's local and never transmitted to the server.

**Comment by lorezyra** [comment]
Latest update completely fixed this issue: https://github.com/lorezyra/Richie2.com/commit/8931eb080b37578a91865e3c0cbfb4ecada71ed2
