### ISSUE TITLE
Play.html: add navigation to gallery

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#114]
Related to #77.

- [x] Take inspiration from [stock.adobe.com](https://stock.adobe.com/search/images?load_type=search&native_visual_search=&similar_content_id=&is_recent_search=&search_type=usertyped&k=projects)
- [x] When user clicks the image, a full width `<div>` opens below the image to reveal the details.
- [x] Next to the close button provide a `<` (back) and `>` forward button.
- [x] When filter is applied, use JS to update the button references.

* After image click, screen expands below clicked image with more details.
![Screen Shot 2021-07-18 at 22 54 45](https://user-images.githubusercontent.com/1673222/126070162-a137cd76-58d7-4979-aa65-bc23deba8a18.png)

**Comment by lorezyra** [comment]
@Asem-prg,

Is there no way to do the filtering in a single loop?  3 for-loops for `inputsArr` looks like WET-code. 

https://github.com/lorezyra/Richie2.com/blob/5be411f3bc998cf110e1a1ccea6ad15d51353aaf/assets/js/lazyImg.js#L138-L160

**Comment by Asem-prg** [comment]
The first two for loops are modifying `inputsArr` it's self, because of that `inputs|Arr`.length is changing, So I separated  them from the last for loop. 

I don't have a way to merge them more than once.

**Comment by lorezyra** [comment]
Would `currentPosition = inputsArr.indexOf(currentItem);` work? 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

**Comment by Asem-prg** [comment]
> Would `currentPosition = inputsArr.indexOf(currentItem);` work? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

It wouldn't work because `inputsArr` is an array of input elements, but `currentItem` is an `id` of the input element. It will work if we have an array of ids, but will need to add extra lines of codes

**Comment by lorezyra** [comment]
For mobile view, could you add a wider margin between the nav/close buttons? It's too easy to tap the wrong button.
