### ISSUE TITLE
NavBar blocked by Safari tab bar

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#119]
- [x] Need to move the NavBar further up. Currently all buttons are blocked by iOS home bar.
- [x] Need to monitor the `window.resize` event on iOS users. If the size changes, then need to move the NavBar up so it's not blocked by Safari tabs or the iOS home bar. 
- The bottom 20px are apparently only usable for the home-bar and Safari tabs. But can adjust the navbar height on resize... We can probably place the copyright info there as it's static content.

![IMG_0682-2](https://user-images.githubusercontent.com/1673222/162979170-6190b014-f1b4-4059-bc3c-c33567a6abde.png)

## Examples of the UI
![](https://images.macrumors.com/t/b0M8TjMf0IQwo61xOuQkHz1KKjg=/400x0/filters:quality(90)/article-new/2021/08/safari-show-bottom-tab-bar-ios-15-option.jpg?lossy)
![](https://i0.wp.com/9to5mac.com/wp-content/uploads/sites/6/2021/08/how-safari-in-ios-15-works-2.jpg?w=2000&quality=82&strip=all&ssl=1)
![](https://www.cultofmac.com/ezoimgfmt/cdn.cultofmac.com/wp-content/uploads/2021/08/67F10214-B2D7-4523-9359-AF8D6314FF0F-1536x864.jpeg?ezimgfmt=ng%3Awebp%2Fngcb21)

## Reference:
 * https://stackoverflow.com/questions/28162364/javascript-detect-when-ios-browser-addres-navigation-show-up
 * https://9to5mac.com/2021/10/29/how-safari-in-ios-15-works/
 * https://samuelkraft.com/blog/safari-15-bottom-tab-bars-web
 * https://samuelkraft.com/blog/safari-15-bottom-tab-bars-web/twitter-good.mp4

**Comment by lorezyra** [comment]
Look at how Twitter handles this.
![DF255B5E-1AA6-4E7C-BD8E-63CC3682A033](https://user-images.githubusercontent.com/1673222/163296319-a5993c38-7619-421b-be37-e800a02a9d3d.png)

When user scrolls up or taps the navbar, the UI moves with the `resize` event.

**Comment by lorezyra** [comment]
I like the proposed navBar design change. 

![IMG_0719 720-1](https://user-images.githubusercontent.com/1673222/164128327-05e9c197-6cc9-4603-9e56-f025cb59a6a5.png)


However, it still needs to listen to the body/`window.resize` event to automatically move the navbar up (or down)

**Comment by AsemAlhaidary** [comment]
Happy to hear that you like it.

Umm, I see the problem didn't fix yet.

**Comment by lorezyra** [comment]
Looks great and operates well.
