### ISSUE TITLE
Configure BLOG theme

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#18]
Design should be consistent with RichieBartlett.com...

- see: https://hexo.io/docs/themes
- example theme: https://github.com/SuperKieran/TKL

**Comment by lorezyra** [comment]
I really like the layout of Medium.com articles.  Would like to customize it for my site.

**Comment by Asem-prg** [comment]
I decided to edit the "theme2.richiebartlett.com" theme to create the new the new theme "2022.richiebartlett.com".

After reading "theme2.richiebartlett.com" carefully I realized that It will need a lot of work and time to implement all the functions and features if I will create the new theme from scratch.

But now I have a good understanding of the structure of "theme2.richiebartlett.com" and I am able to edit it and control its parts.

**Comment by lorezyra** [comment]
Sometimes, it's better to start on a "green field" (or "blank slate") than to have to band-aid an existing software. By using the old theme as a guide, you can build from a new (empty) theme. While this method may initially seem to take longer, it may be easier to see faster progress. Building from scratch enables you to fully understand how the software was built. And, thus make changes quickly. (Rather than spending days trying to understand why something is broken...)

If we were making minor tweaks, then building on-top of the existing theme makes more sense. However, I suspect you will find yourself in a corner when all the old stuff (from the previous programmer) collide with the goals of our design.

**Comment by Asem-prg** [comment]
I was worried about the time and it will take a longer period than editing it. Otherwise when I want to build something I always prefer to build it from scratch, building from scratch allows me to control each part on my site easily and design my site in the way that I like to design. By building a website from scratch we will be able to build it in a "Mobile first" way

But now I will start to build a new website theme from scratch :thumbsup:

**Comment by Asem-prg** [comment]
I will add `ar.yml` language after finishing the navbar menu

**Comment by Asem-prg** [comment]
I did not directly reference the SVG file because I'm using css variables `var(--variable)` inside the SVG code to be effected by theme mode easily, If I referenced the svg file It will need additional JS code to do the job

**Comment by lorezyra** [comment]
In the NavBar, don't forget to include the search button.

**Comment by lorezyra** [comment]
Need to close this issue and make new issues that more narrowly focus on what needs to be done.
