### ISSUE TITLE
index.html

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#2]
- [x] This landing page will prominently feature my photo covering a good portion of the viewable space (on PC & iPad) with animations that invite the user to select work or play. Will need mobile version as well.
- [x] Use: ``` Father | Entrepreneur | Solutions Architect ``` instead of "A Solutions Architect and Entrepreneur"
- [x] Should only animate if user changes mouse selection between either side of the screen (work / play).
- [x] There should be three main sections on the home page of the main body: Work, (my static photo), & Play... 
If user keeps the mouse in the center, then they see the inital photo. Otherwise moving between work & play will display a different photo for each.
- [x] I _really like_ this site design: https://linusbohman.se/ . **However, I'm open to other interesting designs.**
![Screen Shot 2021-05-16 at 20 57 14](https://user-images.githubusercontent.com/1673222/118396218-7551c500-b689-11eb-8690-d3bff4724de7.png)
- [x] Should be able to scroll down to reveal the footer section.

**Comment by lorezyra** [comment]
Should be able to scroll down to reveal the footer section.

**Comment by lorezyra** [comment]
Should be able to scroll down to reveal the footer section.

**Comment by lorezyra** [comment]
- [ ] Should be able to scroll down to reveal the footer section.

**Comment by lorezyra** [comment]
For the footer, can we remove the underline on the mouseover event and use a different background color for the link? Something that highlights the link instead of underlining it.

**Comment by lorezyra** [comment]
The up-arrow in the footer... Could we add a circular background with a shadow to make it become a button so it's obvious to the user that it will take them to the top of the screen?

**Comment by lorezyra** [comment]
For the menu at the top, can we change the background opacity to 80%?

**Comment by lorezyra** [comment]
Let's add my name suffix to the menu in the left corner so it reads: ```Richie Bartlett, Jr.```

**Comment by lorezyra** [comment]
In the footer section, can we add ``` Father | Entrepreneur | Solutions Architect ``` under my name?

**Comment by Asem-prg** [comment]
For the footer links, Since we will make a background for the links instead of the under line, I'd prefer to arrange the links and the title to the left instead of center.

**Comment by Asem-prg** [comment]
> The up-arrow in the footer... Could we add a circular background with a shadow to make it become a button so it's obvious to the user that it will take them to the top of the screen?

For the up arrow, this is just a basic design, and I am planning to make it look more like a button, and I will make it appear when the user scroll down for a specific value, and it will be fixed on down left corner.

**Comment by Asem-prg** [comment]
> For the menu at the top, can we change the background opacity to 80%?

How about to make it change it self when the user scroll down, and I will give it something kind like a little shadow in the bottom.

**Comment by Asem-prg** [comment]
> In the footer section, can we add `Father | Entrepreneur | Solutions Architect` under my name?

Ok.

**Comment by lorezyra** [comment]
> For the footer links, Since we will make a background for the links instead of the under line, I'd prefer to arrange the links and the title to the left instead of center.

That's fine.

**Comment by lorezyra** [comment]
- The cookie notification needs a button to see "cookie policy" next to the "Accept" button.


- For the mobile menu, can you change the background opacity to 80%?


- When the up-arrow is near the bottom of the footer, can you add a CSS rule to ensure it never goes below -200px (or so)? The arrow is too close to the social buttons and would be too hard for old fingers to tap.


- And for ```© Copyrights 2021 Richie Bartlett, Jr. - All rights reserved.```
Can you break it up so in iPhone view it is displayed on 3 lines?
```
Copyright 2021 ©
RichieBartlett.com
All rights reserved.
```

**Comment by lorezyra** [comment]
As we have built the index page, I will close this issue... However, the bugs for this page will be moved to individual issues.
