### ISSUE TITLE
Design card layout for each post (small screens)

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#28]
Specifications of the card:
- [x] Each post should have an image to represent the post. If no image is defined in the front-matter of the post, then use a default image. (Will need to create this image.)
- [x] Must display created date
- [x] Display title
- [x] display tags
- [x] display category
- [x] display excerpt (this is not the full post text)
- ~~display word count~~
- ~~display estimated read time~~
- ~~Pin icon for when a post is stickied to the home page.~~ This is like having a featured post on the website.

**Comment by lorezyra** [comment]
Great card layout for posts:  ``` Bamboo ``` theme
![Screen Shot 2021-05-27 at 0 20 50](https://user-images.githubusercontent.com/1673222/119686877-b44dfa80-be81-11eb-9532-98af5023f4c6.png)

**Comment by lorezyra** [comment]
Great card layout for posts:  ``` Butterfly ``` theme
![Screen Shot 2021-05-27 at 0 29 15](https://user-images.githubusercontent.com/1673222/119688084-a5b41300-be82-11eb-8847-94c270d60a95.png)

**Comment by lorezyra** [comment]
Worth mentioning: 

- https://sanonz.github.io/

**Comment by lorezyra** [comment]
These horizontal card designs would be perfect for the smaller screens like the iPad mini and iPhones.

**Comment by lorezyra** [comment]
New York Times has a decent card layout too.
![Screen Shot 2021-05-27 at 12 31 43](https://user-images.githubusercontent.com/1673222/119761875-961ae580-bee7-11eb-897b-efa5d7627494.png)

**Comment by lorezyra** [comment]
https://codepen.io/FlorinPop17/pen/dyPvNKK
![Screen Shot 2021-05-27 at 12 46 26](https://user-images.githubusercontent.com/1673222/119762944-987e3f00-bee9-11eb-8493-3706537e6748.png)

**Comment by lorezyra** [comment]
- First draft:
![iPhone 12 Pro Max – blog cards](https://user-images.githubusercontent.com/1673222/119941437-9096cb80-bfcb-11eb-81a0-2c0e8769a4d8.png)

**Comment by lorezyra** [comment]
See the following commits:
 - https://github.com/lorezyra/blog.RichieBartlett.com/commit/f543017e8b5b14132d64d3663db26fea64019b7f
 - https://github.com/lorezyra/blog.RichieBartlett.com/commit/09517db4235d1a2ce21abd16315db8a32f8f0e46
 - https://github.com/lorezyra/blog.RichieBartlett.com/commit/473bcb71a290628135e410c9865d252575d91672
 - https://github.com/lorezyra/blog.RichieBartlett.com/commit/d078a0b764bc39d761a3864492cbbc3cbb7442f0

**Comment by Asem-prg** [comment]
From this issue I see that you don't need the Interact bar (Like, comment, share), right?

**Comment by AsemAlhaidary** [comment]
Are you sure you want to adopt this design? I think that the date of publication will not be distinguished and virtually as required

**Comment by lorezyra** [comment]
Yeah, the date is not as important as the post itself. For a blog post design, we should minimize or remove anything that takes away from the focus of the blog. In this case, the most critical elements are: post image, title, and excerpt. The rest somewhat add to the post value, but should not take away the focus of the user.

**Comment by AsemAlhaidary** [comment]
Yeah your right, in case we want to draw our users focus on the post itself, then we should underestimate the importance of displaying the date.

**Comment by AsemAlhaidary** [comment]
Sorry, I have closed it by mistake.

**Comment by lorezyra** [comment]
Can you take another look at https://github.com/lorezyra/Richie2.com/issues/28#issuecomment-1096703814 ? I have changed the `tag` design to be more subtle. 

Plus, need to use `post.excerpt` (If present) as the description of the post.

**Comment by lorezyra** [comment]
For the tags, let's have the basic tag appear with the `theme` color for text. Only when user taps or hovers over the tag should the background change to the gray color. Can you update that?


![image](https://user-images.githubusercontent.com/1673222/165006409-43695563-ba92-457f-98bb-a1e26679b3d2.png)

**Comment by lorezyra** [comment]
Close, but not quite.  All the tags should default to the way "tag0" appear in the previous comment. "Tag2" represents what it should appear when hover or active.

Remember that we don't want to distract the user from the post content.

**Comment by AsemAlhaidary** [comment]
In that case, we don't need the script

**Comment by lorezyra** [comment]
Interesting. Maybe we can use that script somewhere else. Just not for the tags.

Looks good!
