### ISSUE TITLE
Design article layout for each post page

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#29]
I like how https://Medium.com is laid out for its articles. Perhaps we could do something similar?

Top needs to have post.title along with the following:

- [x] post.subTitle
- [x] published date 📅
- [x] word.count
- [x] read time estimate (Time to read -> ⏳)
- [x] category 📂
- [x] bread crumbs

Body of the post:

- [x] ToC (table of contents) for long posts (if no ToC defined in front-matter, don't render ToC)
- [x] Needs to consume at least 75% of the page width
- [x] Be easy to read

Bottom of the post needs:

- [x] tips link with message like: "buy me a coffee"
- [x] tags (with a single tag icon before all listed tags)
- [x] modified date
- [x] creative commons license notice
- [x] include social media icons for sharing
- [x] comment section:  provide option to display Disqus widget

Similar to this: https://entrepreneurshandbook.co/how-i-slowly-became-a-middle-class-millionaire-bd621529fb0f?source=home---------4-73--------------------d17f8438_a5e5_4b85_9a2e_9deb917cd54c-------&gi=72f5a3a39450

**Comment by lorezyra** [comment]
Another good layout: https://v-vincen.life/en/Hexo-Theme-LiveMyLife/

**Comment by lorezyra** [comment]
Worth mentioning:

- https://www.ieclipse.cn/en/2018/01/29/PHP/php-wnl/

**Comment by lorezyra** [comment]
Consider how Medium.com has designed their site: https://blog.medium.com/a-better-medium-com-d468104ebb90

**Comment by lorezyra** [comment]
Current XD file needs to have a search bar for categories and tags. Plus, there should be a general search icon for all posts on the site.

Can you add that to the design?

**Comment by lorezyra** [comment]
On Mobile view, Let's add the statistics there. Desktop has more real estate, so it's okay to leave it in the sidebar. Also, lets make my icon bigger and centered at the top for mobile menu. No need to create a circle around the image. It's fine to display the URL with my portrait. And, we can drop the "Richie Bartlett" and "Japan" texts from the menu.

<img width="444" alt="image" src="https://user-images.githubusercontent.com/1673222/154803213-5c2ea087-c19f-40bb-870a-2c4bb9a0f89b.png">

**Comment by lorezyra** [comment]
What's the ellipsis menu (bottom-right corner) for on the post?
Do you have a feature in mind?

<img width="499" alt="image" src="https://user-images.githubusercontent.com/1673222/154803568-e29cb7da-3e5e-4482-b497-1a7c5e0f8c64.png">

**Comment by lorezyra** [comment]
Regarding the categories, I see them the same as the folder view. Similar to this:
![image](https://user-images.githubusercontent.com/1673222/154803915-42bfbdc8-f6b1-4ab2-85ff-f6c343878fd9.png)

And on the posts, categories should look like a "bread crumb" (path) similar to this:
![image](https://user-images.githubusercontent.com/1673222/154803907-83c5ccd2-a221-4703-970c-319dc358cd2d.png)

**Comment by lorezyra** [comment]
Also, it's better to design for MOBILE FIRST, then scale it up to larger devices. Lets keep this in mind.

**Comment by Asem-prg** [comment]
The ellipsis on the posts it's for "more options" if needed. If you will have more writers on your blog each one will have his own account, the user can choose from multiple options from that icon, like if the user wants to mute the messages from a special and so on.

**Comment by Asem-prg** [comment]
Yes, this time we will design for "Mobile first"

**Comment by lorezyra** [comment]
Regarding the ellipsis menu icon, I don't see a need for it. While I have entries from other blogs, they won't be writing on my blog. I simply copy&paste articles of interest.

---

Also, I'd like to change how the copyright section displays ownership. If I write it, then I own it. However, if I'm copy&pasting from other source, then I wish to properly credit that source. This will require a few more variables added to the front-matter in the MD file. Then we need to update the post design to include this. 

The variables should include:
 * source-url
 * source-author
 * source-publishDate

If ```copyright: false``` then nothing is displayed. When ```true``` and ```source-url : ''``` , display my copyright details. Otherwise, show where I copied the article.

**Comment by lorezyra** [comment]
Can you add how the menu would appear while the user is scrolling up (both PC & mobile)?

**Comment by lorezyra** [comment]
FYI: this may help you in troubleshooting hexo themes:
[https://stackoverflow.com/questions/57125171/how-to-debug-inspect-hexo-blog](https://www.freelancer.com/users/l.php?url=https:%2F%2Fstackoverflow.com%2Fquestions%2F57125171%2Fhow-to-debug-inspect-hexo-blog&sig=ffac2c35744bb9d8297cfb518f571b6526cf282ccc00675af9bbe993d09c7b71)

**Comment by lorezyra** [comment]
Still missing the theme controls. Can you add?

**Comment by Asem-prg** [comment]
Menu on scroll and search section was added

**Comment by Asem-prg** [comment]
Sure, I was thinking since we want to switch only between (day/night) themes, it's better to add a simple fixed floating button on the bottom left corner of each mobile & desktop screens, how would it be like?

**Comment by lorezyra** [comment]
Let's make it the same as the main website.

**Comment by lorezyra** [comment]
Can we make the mobile theme selection the same as the mobile version of the main site? Where the theme is on the mobile menu?

**Comment by lorezyra** [comment]
Let's consider a different approach for the blog design on mobile. Both Instagram & FaceBook have a good design layout for the UI on mobile. Could you create a new mobile design similar to this?

![07842E58-BEA0-4AF4-9846-059B352822ED](https://user-images.githubusercontent.com/1673222/155910281-b2e46a12-4363-459c-a5a7-6e04447c2ae9.png)
![4A0B1E7C-D632-4EC4-8360-6AE94D9264D9](https://user-images.githubusercontent.com/1673222/155910299-c75bb2b7-22b4-4944-a46e-3a9481b18cdc.png)
![E8E6A400-4660-4905-990C-F46D82CC566F_1_101_o](https://user-images.githubusercontent.com/1673222/155910682-3b11cf1b-8810-4657-bc3d-32efd0d8ad9c.jpeg)
![70DD33FB-EA8F-4D43-A0AD-80CE5D0EFA90_1_101_o](https://user-images.githubusercontent.com/1673222/155910694-cffdfcbc-32d7-4a4a-b0fc-bb8adc7fefb0.jpeg)
![8CA2DCF1-95A0-4E68-8C4E-72E66A31CA44_1_101_o](https://user-images.githubusercontent.com/1673222/155910698-937d667b-cc5d-4ba9-b016-15e12678f76a.jpeg)


For the share menu, something similar to this?
![5660F6D6-43BD-49D9-BB08-A20139C3E56F](https://user-images.githubusercontent.com/1673222/155910324-8b87ffd4-3c8e-479e-bd10-2746f76bc730.png)

When user clicks on "like" or "comment," we can simply expand the view to show discus integrated plugin. Otherwise, Discus is hidden from view. What do you think?

**Comment by Asem-prg** [comment]
Okay, I will create a new design for the blog besides the current design.

**Comment by Asem-prg** [comment]
For the menu, How about moving it to the bottom of the screen and showing the icons like Facebook, Instagram, and others?

**Comment by Asem-prg** [comment]
If we designed the comment section as you've mentioned then we can dispense the separated post page, right?
I think it's a good idea.

**Comment by lorezyra** [comment]
> For the menu, How about moving it to the bottom of the screen and showing the icons like Facebook, Instagram, and others?

Yes, let's see what that design would look like. (Keep the previous design for reference.)



> If we designed the comment section as you've mentioned then we can dispense the separated post page, right? I think it's a good idea.

Still need the post page as shared links will direct users to a single post and not the home page...

**Comment by Asem-prg** [comment]
When a user clicks on the comment button, the Disqus section will appear.

I've used a placeholder photo for that.

**Comment by lorezyra** [comment]
Let's move the Search button to the bottom mobile menu.
Move the theme selection to the (top) menu on mobile.

![BD0EAEC1-A981-492D-B551-F32E946F7576](https://user-images.githubusercontent.com/1673222/156271320-838f021d-9ab0-4011-9f23-348c0da8e71f.png)


Also, the top menu should not hide/cover the bottom menu.

**Comment by lorezyra** [comment]
For the "Facebook Menu," what does "More Options" do?

**Comment by lorezyra** [comment]
When user taps the comment button on the feed (home/tag/category) page, what does it look like? 
On the post page, we don't hide it (Disqus). Can you add a frame in XD to illustrate that?

**Comment by lorezyra** [comment]
Can you show what the "Night" view for the post and home page would look like?

**Comment by Asem-prg** [comment]
> For the "Facebook Menu," what does "More Options" do?

It's just a place holder for new choices like "Recommended", we can remove it if we won't use it

**Comment by Asem-prg** [comment]
> When user taps the comment button on the feed (home/tag/category) page, what does it look like? On the post page, we don't hide it (Disqus). Can you add a frame in XD to illustrate that?

There is a separated frame to illustrate that

![image](https://user-images.githubusercontent.com/68165112/156376146-93d3101c-7693-4ec3-b413-aebb04bd3678.png)

**Comment by lorezyra** [comment]
Search icon is _too_ close to the menu button.
Can you move the search button to the bottom with the other 5 icons?

**Comment by Asem-prg** [comment]
The search icon moved to the bottom navbar

**Comment by lorezyra** [comment]
Let's update the color scheme of the icons when selected. Simply changing the icon from white to black isn't good enough. Let's add a background to the active icon.

**Comment by Asem-prg** [comment]
Ok, how about to change icon color to orange, and change it's background?

**Comment by lorezyra** [comment]
When user taps the navbar search icon, it should be highlighted differently from the rest of the icons.
<img width="372" alt="image" src="https://user-images.githubusercontent.com/1673222/156855868-0f850473-45c6-438b-b17a-e844809bf08b.png">

Plus, need to add a 2nd close button at the top-right corner to the search window. Similar to this:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/1673222/156862708-bbb603d6-f7a5-448f-90ab-a846440f0988.png">

**Comment by lorezyra** [comment]
Also, lets change the navbar to be more like this. We don't need an icon for the post page. Post page can use the "Home" icon. If user taps the home icon, then it scrolls to the top of the home page.
Plus the menu should use the "accordion" style menu where options expand to show more.

<img width="432" alt="image" src="https://user-images.githubusercontent.com/1673222/156871017-203bc957-4a94-4ea5-a89b-38abfd2780bd.png">

What are your thoughts?

**Comment by lorezyra** [comment]
For mobile menu, lets also add the links from the footer there. As the only place they could find the footer is on the non-home pages.

**Comment by Asem-prg** [comment]
I think we don't have to name "Theme/Statistics" sections by their names, the user can know the purpose of the design by himself, and the design can explain its job.

**Comment by lorezyra** [comment]
The idea behind an "accordion" menu is that everything is hidden until tapped. In this case, we have many items to display. So, we need to hide theme & statistics. Take note of the ">" icon on the right side of the menu items. 

Otherwise, we have a long menu that requires scrolling. 

Can you suggest a better way?

**Comment by lorezyra** [comment]
As I illustrated above [above](https://github.com/lorezyra/Richie2.com/issues/29#issuecomment-1059705172), we don't need 6 icons in the navbar. Plus, as I'm not a well known website, I must have text added to the icons to provide reference for each function. Additionally, I think we should make the icons larger.

Can you update the design?

**Comment by lorezyra** [comment]
I like your close button on the search window. However, I think it's better to have the search icon separate of the text field. 

Can you update it more like this?
<img width="721" alt="image" src="https://user-images.githubusercontent.com/1673222/156862708-bbb603d6-f7a5-448f-90ab-a846440f0988.png">

**Comment by Asem-prg** [comment]
New updates with "accordion" menu, and more

**Comment by lorezyra** [comment]
Can you update the desktop search design to match the mobile?

**Comment by lorezyra** [comment]
On the `Post - Mobile - Facebook` frame, can we add the navigation for "next" and "prev" post?
There should be an obvious icon for the user to see "next" and "prev" ... Can you design that?
![image](https://user-images.githubusercontent.com/1673222/157157941-c5cc8ff8-cccb-4d5f-8527-8bc17117b16a.png)

---

Under the `statistics` section of the menu, let's add the following:
- total reading 📖
- total visits 👨🏻‍🦰
- Visitor count #

<img width="746" alt="image" src="https://user-images.githubusercontent.com/1673222/157158610-f14b9592-c56c-4a33-acd3-479985d877cc.png">

---

For the social network section, add the [RSS feed (atom) icon](https://en.wikipedia.org/wiki/Atom_(Web_standard)) somewhere. Plus the email icon. 
_Note, not required to keep these icons in a straight line. If needed, it can be set to a grid._

---
Can you update the Disque view for mobile users?

![image](https://user-images.githubusercontent.com/1673222/157160505-c01adb53-a9d4-4972-bdb2-56f515984e00.png)

**Comment by lorezyra** [comment]
Additionally, I think we need to redesign the post page a bit more. When I look the the home page with the post feeds, the posts take 100% of the screen-width. However, in your design, there are two sets of margins - the page and the post-content.  Some of my post are very long and the added margins would increase that length. Can you propose another layout?

**Comment by lorezyra** [comment]
Also, lets add an icon for the Toc (Table of Contents) for the user to quickly jump ahead in the post. By default, the ToC will be hidden until the icon is tapped to slide it in. If the `toc: false` then we don't show the icon.

Can you add this?

**Comment by lorezyra** [comment]
On the Desktop view, can you add the navbar icons to the top menu?

**Comment by Asem-prg** [comment]
> On the Desktop view, can you add the navbar icons to the top menu?

Do you mean you want it to be look like mobile menu?

**Comment by Asem-prg** [comment]
I have updated the statistics section on the desktop. On mobile it will be exactly the same design, I am telling you that because we have expanded only the `Theme` section on the accordion menu.

**Comment by Asem-prg** [comment]
There are new Updates, can you review them please?

**Comment by lorezyra** [comment]
> > On the Desktop view, can you add the navbar icons to the top menu?
> 
> Do you mean you want it to be look like mobile menu?

If you look at the existing design, you can see what I'm referring to...
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/1673222/158000094-caf74e06-54b4-4205-a19e-95ae9de8d528.png">

**Comment by lorezyra** [comment]
On the post page, we should really show the post img and text directly on the page... Your text buttons don't really give the user a reason to navigate to the prev/next pages. Easy to not care when they don't see why they should see the prev/next post.

![image](https://user-images.githubusercontent.com/1673222/157157941-c5cc8ff8-cccb-4d5f-8527-8bc17117b16a.png)


However, we can definitely update the look of the buttons. I like having the background match the post img... but we can change the icons to match the size of the button and play with the text a bit.

**Comment by Asem-prg** [comment]
Sure, I will do updates to next/prev buttons

**Comment by Asem-prg** [comment]
Previous/Next buttons have been updated

**Comment by lorezyra** [comment]
How about something a bit more creative?

<img width="490" alt="image" src="https://user-images.githubusercontent.com/1673222/158052040-1853637a-6239-464b-b2a3-c7c50c1fb26a.png">

Can you suggest better?

**Comment by Asem-prg** [comment]
What's your opinion on my idea?

**Comment by lorezyra** [comment]
Better. However, I don't see the need for the text-based arrows if the image is the arrow.

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1673222/158057916-76c0ea08-57e3-40d4-b957-e54306bd0de6.png">

Hmm... do we really need the prev/next text here if the shape already suggested direction?

**Comment by lorezyra** [comment]
In designing things for other people, keep in mind about the human brain. Due to the physiology of our brains, we all will recognize color long before shape. Shape before text... Text must be processed before comprehension. Then finally, we can make a decision on what to do.

**Comment by Asem-prg** [comment]
Great note, I benefited from that, I'll make some edits right away

**Comment by Asem-prg** [comment]
Can you check that please?

**Comment by lorezyra** [comment]
Let's do similar for Desktop as well.

**Comment by Asem-prg** [comment]
It's the same on desktop top, When the shape ia square there will be a text to describe the direction. But When it's in arrow shape the text will disappear.

**Comment by lorezyra** [comment]
Oh, on the Statistics panel, make sure the icons match the navbar icons. Categories should use the folder icon.

Let's use the same design philosophy on desktop as we do for mobile. I like your arrow idea. I think it should be used on desktop as well.

**Comment by Asem-prg** [comment]
Okay

**Comment by Asem-prg** [comment]
Done

**Comment by lorezyra** [comment]
Have any thoughts on this design?

<img width="590" alt="Screen Shot 2022-03-14 at 12 21 11" src="https://user-images.githubusercontent.com/1673222/158099387-01773da4-2669-41c1-aeef-cbc22132e64a.png">

**Comment by lorezyra** [comment]
I like this a bit more for the post page. What do you think?

<img width="522" alt="image" src="https://user-images.githubusercontent.com/1673222/158105531-00936e34-15b6-4614-8c1f-b2b5075bcad5.png">

**Comment by Asem-prg** [comment]
I can't open the XD file because you've edited it in a newer version of Adobe XD, I am trying to update my software.

**Comment by Asem-prg** [comment]
Nice design!

I saw the xd design after updating my software, I think it's better a bit than before, I will add some spaces in the design.
