### ISSUE TITLE
tips.html

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#3]
- [x] Should model this page: [https://Technocracy.Works/donate.html](https://raw.githubusercontent.com/lorezyra/www.technocracy.works/Production/donate.html)
- [x] Will share the Bitcoin & Ethereum addresses later. I won't be using the old wallets for my personal site.
- [x] Bitcoin details:
```
Payment information
URI: bitcoin:BC1QCR5LFGEZ89E04XL89XAYG34CMJEQ4NZ0WGL464?label=RichieBartlett.com
Address: bc1qcr5lfgez89e04xl89xayg34cmjeq4nz0wgl464
Label: RichieBartlett.com
```
- [x] Ethereum details:
```
Payment information
URI: ethereum:0xC83107B60f42B5211727c7d7D1F9135ada395Ad0?label=RichieBartlett.com
Address: 0xC83107B60f42B5211727c7d7D1F9135ada395Ad0
Label: RichieBartlett.com
```
- [x] PayPal details:
```
Payment information
URI: https://paypal.me/pools/c/8yAxZgWtxX
```

**Comment by lorezyra** [comment]
For the paragraph at the top, can we add a background with 50% opacity to make the text easier to read?

**Comment by Asem-prg** [comment]
To where you want the links under "to-donate" class redirect the users?

**Comment by lorezyra** [comment]
Can you copy the links on the https://Technocracy.Works/donate.html page?

**Comment by lorezyra** [comment]
Can we change the focus of the `donate` button to display the text (`Select Your Preferred Method
`) above the bitcoin payment?

**Comment by Asem-prg** [comment]
Sorry I didn't understand what you mean

**Comment by lorezyra** [comment]
<img width="692" alt="Screen Shot 2021-07-19 at 19 43 13" src="https://user-images.githubusercontent.com/1673222/126148493-db5298a3-bce8-4bc2-90d2-efa022652b82.png">

**Comment by lorezyra** [comment]
> When user clicks the `donate` button, Can we focus on the text (`Select Your Preferred Method `) above the bitcoin payment?

I see what's happening... You have correctly assigned the id `redirect`, but due to the menu, the text gets hidden. Perhaps we should create a `<div>` above the text such that it's not hidden?

**Comment by lorezyra** [comment]
Also, can you add the icons to the sections below the crypto links? Just like you illustrated in the XD file?

**Comment by lorezyra** [comment]
Looks great on mobile. However, can we move the icons to the left side of the container for PC view?

**Comment by lorezyra** [comment]
Awesome!
