### ISSUE TITLE
Enhance website images for cards & banners

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#33]
- https://blog.hootsuite.com/social-media-image-sizes-guide/
![image](https://user-images.githubusercontent.com/1673222/119930714-eadb6080-bfba-11eb-8333-cc7c5fe7ec71.png)

- [ ] read this blog and keep it bookmarked for your future designs. (Then you can close this issue.)

**Comment by AsemAlhaidary** [comment]
Thank you very much, I really liked this and benefited from it.
