### ISSUE TITLE
Mobile menu design

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#39]
This is related to issue #2, but affects all pages.
- From the attached photo, you can see the screenshots on the left side.
- On the right side, you can see what is closer to my vision of this menu.
![Mobile menu notes](https://user-images.githubusercontent.com/1673222/120891167-0a6d2b80-c642-11eb-9e43-9631fbb5da74.png)

- [x] Fix opacity issues for mobile safari browsers. Blur is cool, but if it's not supported, then it doesn't look that good. Add additional CSS rules to consider support for safari and firefox. What works in Chrome doesn't always work in other browsers.
- [x] Menu font-size is too small. Not everyone has great eye-sight. Plus, we don't wish to strain the users' eyes trying to navigate around.
- [x] Make the 7 social icons at least 48px x 48px on PC; but 36px x 36px on iPhone
- [x] Move the theme switch to the mobile menu. (Fine to leave it for PC, but gets in the way of reading on iPhone.)

## What Screen Resolutions Are Relevant for Responsive Web Design? [1]

- 360x640 (small mobile): 22.64%
- 1366x768 (average laptop): 11.98%
- 1920x1080 (large desktop): 7.35%
- 375x667 (average mobile): 5%
- 1440x900 (average desktop): 3.17%
- 720x1280 (large mobile): 2.74%

---
[^1] https://www.toptal.com/designers/responsive/responsive-design-best-practices

**Comment by Asem-prg** [comment]
48px x 48px icons are too large for PC
![image](https://user-images.githubusercontent.com/68165112/120927414-66d75600-c6e9-11eb-9968-334750bfd547.png)

**Comment by Asem-prg** [comment]
But 36px x 36px icon looks great on Mobile
![image](https://user-images.githubusercontent.com/68165112/120927509-b289ff80-c6e9-11eb-9df9-f62225c4c190.png)

**Comment by lorezyra** [comment]
> 48px x 48px icons are too large for PC
> ![image](https://user-images.githubusercontent.com/68165112/120927414-66d75600-c6e9-11eb-9968-334750bfd547.png)

 This should be used for the 4K monitor sizes. ```@media query (max-width: 2000px)```

**Comment by lorezyra** [comment]
Having the Theme tray on the mobile menu is one click too many. Let's move the tray to be directly within the mobile menu. Something like this:
![image](https://user-images.githubusercontent.com/1673222/121279171-180b0580-c90f-11eb-8d0b-334e0fb988ea.png)

**Comment by lorezyra** [comment]
Switcher not yet visible on mobile menu.

**Comment by Asem-prg** [comment]
> Switcher not yet visible on mobile menu.
> 
> I see you copied the HTML block for the PC view.
> 
> * Could you consider how to reuse existing elements?
> 
> https://github.com/lorezyra/Richie2.com/blob/ae500f7dd942665c4e59edc84b3736d78dd315ad/index.html#L119
> 
> 
> ![Screen Shot 2021-06-10 at 9 27 10](https://user-images.githubusercontent.com/1673222/121446721-1d2f8980-c9cf-11eb-8ebd-1c4b82abae3d.png)
> * For the mobile theme switch, we should drop the SVG gear, SVG tray, and shadow.
> * Use CSS to style a simple box with a 1px border styled with a 3px border-radius.
> * Add the word `Theme` rotated at -90° along the left side of the switcher. This text can be inside the box.
>   (See my previous [comment](https://github.com/lorezyra/Richie2.com/issues/39#issuecomment-857305888).)

fixed

**Comment by lorezyra** [comment]
As noted in my previous [comment](https://github.com/lorezyra/Richie2.com/issues/39#issuecomment-857305888), could you please add a border around the theme switch?

Something like this:
![image](https://user-images.githubusercontent.com/1673222/121279171-180b0580-c90f-11eb-8d0b-334e0fb988ea.png)


```CSS

    border: 1px solid var(--text-color);
    border-radius: .5em;
```

**Comment by lorezyra** [comment]
Theme switch not hidden on iPhone view...

![IMG_9292](https://user-images.githubusercontent.com/1673222/121618376-9dbeba80-caa1-11eb-92cd-fee2ee77b268.jpeg)

**Comment by Asem-prg** [comment]
> ```css
> (--t
> ```

Working on it

**Comment by Asem-prg** [comment]
> Theme switch not hidden on iPhone view...
> 
> ![IMG_9292](https://user-images.githubusercontent.com/1673222/121618376-9dbeba80-caa1-11eb-92cd-fee2ee77b268.jpeg)

It should be hidden on iPhone. I have tested the page with different Mobile screen sizes

![photo_2021-06-11_07-10-20](https://user-images.githubusercontent.com/68165112/121629836-b2408a00-ca84-11eb-957f-d4bd64b277e8.jpg)

![photo_2021-06-11_07-10-24](https://user-images.githubusercontent.com/68165112/121629881-c4222d00-ca84-11eb-8344-fbcdfd649613.jpg)

**Comment by Asem-prg** [comment]
> > Theme switch not hidden on iPhone view...
> > ![IMG_9292](https://user-images.githubusercontent.com/1673222/121618376-9dbeba80-caa1-11eb-92cd-fee2ee77b268.jpeg)
> 
> It should be hidden on iPhone. I have tested the page with different Mobile screen sizes
> 
> ![photo_2021-06-11_07-10-20](https://user-images.githubusercontent.com/68165112/121629836-b2408a00-ca84-11eb-957f-d4bd64b277e8.jpg)
> 
> ![photo_2021-06-11_07-10-24](https://user-images.githubusercontent.com/68165112/121629881-c4222d00-ca84-11eb-8344-fbcdfd649613.jpg)

I will check if I hade some mistakes, and will add some CSS to include all browsers.

**Comment by lorezyra** [comment]
Don't forget to add the border around the switch. When ready, push the commit.

**Comment by Asem-prg** [comment]
> Don't forget to add the border around the switch. When ready, push the commit.

Done

**Comment by lorezyra** [comment]
Seems to still be present on iPhone:
![IMG_9296](https://user-images.githubusercontent.com/1673222/121658112-fd39bc00-cadb-11eb-96bb-6d1ce03ee6de.jpeg)

**Comment by lorezyra** [comment]
Excellent work!
