### ISSUE TITLE
about.html

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#4]
- [x] Basic contents can be directly copied from the existing site @ RichieBartlett.com
- [x] There should be a subtle section to sign-up for a newsletter. Users can volunteer their email.

- ~_this could be combined with the index.html page provided the right design._~

**Comment by lorezyra** [comment]
Is it possible to animate the waves at the top of this page?

**Comment by Asem-prg** [comment]
> Is it possible to animate the waves at the top of this page?
> 
> See: https://youtu.be/5YGge0RaCx8

Okay, I will do that.

**Comment by lorezyra** [comment]
Need to improve the topography of the `Quick facts` section.
Can we push the "Quick Facts" title down away from the waves and closer to the table of text?

**Comment by Asem-prg** [comment]
> ## Nav-Menu
> * [x]  Add a highlight/outline or something to make it obvious that we are on the About page.
> * User needs to know the current page (from the menu).
> 
> ## Layout
> * Strongly recommend building "mobile-first" designs and then work on desktop designs.
>   
>   * See https://youtu.be/0ohtVzCSHqs
> * Desktop view is starting to come together, but it looks bad on iPhone.
> 
> * [ ]  Let's remove the text from the SVG and apply directly in the HTML document.
> * IF I should need to update that text, having it in HTML is **much** easier.
> 
> ## Professional Skills
> * [ ]   The `line-height` of "Professional Skills" should decrease to `0.9`.
> * [ ]   Let's change the text paragraphs to `justified-center`.
>   
>   * [ ]   And, double-check the spacing between words.
>   * [ ]   Probably a good idea to increase the line-height to `1.3`.
> 
> ## Quick Facts
> * [ ]   Need to improve the topography of the `Quick facts` section.
> * [ ]   Can we push the "Quick Facts" title down away from the waves and closer to the table of text?
>   
>   * [ ]   Recommend changing `margin-bottom` to:
> 
> ```css
> margin-top: 4em;
> margin-bottom: 1em;
> ```

I will work on that

**Comment by lorezyra** [comment]
Let's change the active underline to ```var(--bg-special-color)```.

**Comment by Asem-prg** [comment]
To have a know in what I am doing, I design the static pages in the first, after that I will do the animations to the pages.

**Comment by lorezyra** [comment]
Cool that you got the waves moving. But they are too fast. 

Let's slow them down to, say, 6x slower. So, the 10sec animation should be 60s (and 48s & 36s).

Otherwise, the waves become too distracting.

**Comment by lorezyra** [comment]
Looks good.
