### ISSUE TITLE
iPhone view: Swipe text

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#42]
- [x] Change the color of the ```Swipe``` text to gray.
- [x] Change the arrow color to gray as well.

- In Night mode, the white color is too bright and distracting. It should be a suggestion for navigation.
- Same for Day mode, the black offers TOO much contrast. 
- These navigation helpers should be subtle.

![Screen Shot 2021-06-05 at 10 19 29](https://user-images.githubusercontent.com/1673222/120894446-5aa0b980-c653-11eb-86e0-d55f4da0edfb.png)
![Screen Shot 2021-06-05 at 10 27 26](https://user-images.githubusercontent.com/1673222/120894456-642a2180-c653-11eb-8cf3-7889c8c82451.png)

**Comment by Asem-prg** [comment]
Fixed

**Comment by lorezyra** [comment]
Which commit?

**Comment by lorezyra** [comment]
@Asem-prg , Please don't forget to reference the issue number in your commit message.
Found in https://github.com/lorezyra/Richie2.com/commit/3fab702451de8590a438ebbcd24cab71c2455aab.

**Comment by lorezyra** [comment]
- [ ] Let's add an opacity = 85% to this.

**Comment by lorezyra** [comment]
Let's change this to:
```CSS
    --opacity-secondary-text-color: #86868833;
```

**Comment by lorezyra** [comment]
Looks good.
