### ISSUE TITLE
Fix theme bugs

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#43]
Relates to #10 .

- [x] Please save user preference in a cookie. 
- [x] When user loads page, please check cookie. If cookie exists, load preference.
- [x] If no cookie, check local user time and load theme appropriate for the time of day. 
- [x] If between 07:00 and 18:00 local user time, load Day theme. Otherwise keep default Night theme loaded.
- [x] Fix load bug where day theme doesn't completely load.
- [x] When user clicks a theme, hide the theme container.

- initial load bug on iPhone:
![IMG_9271](https://user-images.githubusercontent.com/1673222/120892558-ef061e80-c649-11eb-88ab-7ccec8d0d750.PNG)
- initial load bug on iPhone (shows cookie notification):
![IMG_9272](https://user-images.githubusercontent.com/1673222/120892567-f7f6f000-c649-11eb-8825-14ecd0ad0553.PNG)
- initial load bug on PC:Chrome (small screen):
![Screen Shot 2021-06-05 at 10 27 26](https://user-images.githubusercontent.com/1673222/120892592-178e1880-c64a-11eb-8913-1257d08680a0.png)
- initial load bug on PC:Chrome (regular screen):
![Screen Shot 2021-06-05 at 10 28 39](https://user-images.githubusercontent.com/1673222/120892597-1e1c9000-c64a-11eb-8695-6bfa58042f44.png)
- initial load bug on PC:Chrome (regular screen) looking at footer:
![Screen Shot 2021-06-05 at 10 18 33](https://user-images.githubusercontent.com/1673222/120895926-1bc23200-c65a-11eb-8759-68499e35c71c.png)

- If user selects the night theme and then changes back to day, the layouts and CSS properly load.
![Screen Shot 2021-06-05 at 10 30 17](https://user-images.githubusercontent.com/1673222/120896503-cf2c2600-c65c-11eb-85e3-22e99e9f7772.png)

**Comment by Asem-prg** [comment]
Fixed

**Comment by Asem-prg** [comment]
The cookie will save user experience for tow hours.

Do you want to increase saving time?

**Comment by lorezyra** [comment]
Make the expiration two weeks.

**Comment by lorezyra** [comment]
Also,  When user clicks a theme, hide the theme container.

**Comment by lorezyra** [comment]
Reviewed and complete
