### ISSUE TITLE
Upload all image files

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#47]
- Please upload all the SVG files for all the PNG images used for this site.
- Take note what I did for the QR code images. I uploaded the SVG, small PNG, and large PNG.
   https://github.com/lorezyra/Richie2.com/commit/daf14fabb5ffc5c53ca06b7df18b2237c3734dd9
- These are what we can use in the site. I prefer the SVG files over PNG files as they will scale up very nicely. However, the PNG files are typically smaller in size and best used on the mobile screens.

- [x] Commit all PNG, SVG, JPG, PSD, and illustrator files to the `img` folder.

**Comment by Asem-prg** [comment]
Ok.

**Comment by lorezyra** [comment]
Some images may require rescaling. Therefore, need original images to make those adjustments.
Not all images in the HTML will be PNG. Some will be SVG. Depends on the element and how we need it to scale between screen sizes.

**Comment by lorezyra** [comment]
Good to go.
