### ISSUE TITLE
tips: ThankYou.html

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#48]
- Related to #3.  Need a "Thank you" page anytime someone sends a payment.
See [https://Technocracy.Works/donated.html](https://raw.githubusercontent.com/lorezyra/www.technocracy.works/Production/donated.html) as an example.
- Create a new graphic in the same style as the error pages.

**Comment by lorezyra** [comment]
Let's use this graphic for the ThankYou page: https://github.com/lorezyra/Richie2.com/blob/Dev/assets/img/International_ThankYou.svg

**Comment by lorezyra** [comment]
Need to add text for the user to read. This is required for Paypal and other payment processors to have a "thank you" page. See the example text from https://Technocracy.Works/donated.html.

Maybe add a `div` with a translucent (opacity: 50%?) and the text within that element.

**Comment by lorezyra** [comment]
On Safari, the graphic covers the text. Can you check?

**Comment by lorezyra** [comment]
For the text, let's use the `--text-color` variable instead of a static color.

**Comment by lorezyra** [comment]
For PC view, this page feels "lacking..." Like it's missing a consistent design employed across the other pages. For a "thank you" page, it needs to make the user feel appreciated. 

Perhaps we move the graphic to the top of the page and overlay the text with a blurred background?

**Comment by Asem-prg** [comment]
I will do some thing about that.

**Comment by Asem-prg** [comment]
I guess we replace the SVG image with animated text that says "Thank you" in different languages, and change the layout of the page?

**Comment by lorezyra** [comment]
This is NOT a copy of the email page you created. The international "thank you" SVG is fine. What I'm envisioning is something that doesn't look too plain. The tips page looks good. But the thankyou looks like a poor after-thought.

**Comment by lorezyra** [comment]
looks good
