### ISSUE TITLE
work.html

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#5]
- [x] This page will represent my professional past... a CV/resume of sorts, but focused on highlighted companies and projects I've participated/lead.
- [x] This page's background should be a little brighter than the index page.
- [x] Add section for "We should work together!" with a link to open an email and the basic "mailto:" href prefilled.
- I like the vertical wall for past employers.
- Could also be a vertical timeline graph.

![image](https://user-images.githubusercontent.com/1673222/118399252-3d517e80-b697-11eb-9bed-0ee821899db0.png)

![image](https://user-images.githubusercontent.com/1673222/118399291-7ab60c00-b697-11eb-8c25-e29f1b1d2433.png)

**Comment by Asem-prg** [comment]
Can give me your email account to write it in "mailto:" link please?

**Comment by lorezyra** [comment]
```mailto:rich&#64;Ri&#99;hieBa&#114;t&#108;&#101;&#116;t&#46;&#99;&#111;&#109;?subject=blog```

**Comment by lorezyra** [comment]
Still need to replace the `personal.jpg` image...

**Comment by lorezyra** [comment]
Change the `Download CV` button to `View LinkedIn profile`. I won't be publishing my CV on my website.

**Comment by lorezyra** [comment]
Need to change the card design for the `My Projects` section.

I really like how Kevin Powell did his design: https://blog.richiebartlett.com/2021/0603/work_%E4%BB%95%E4%BA%8B/Projects/Researching-Blog-Design.html#CSS-Card-with-hover-animation-and-mobile-fallback

**Comment by Asem-prg** [comment]
> Still need to replace the `personal.jpg` image...
> Do you have enough photos to create something here?

Of course

**Comment by Asem-prg** [comment]
> Change the `Download CV` button to `View LinkedIn profile`. I won't be publishing my CV on my website.

Okay

**Comment by lorezyra** [comment]
I'm adding the company Logos now. :)

**Comment by Asem-prg** [comment]
> I'm adding the company Logos now. :)

I am interested to see that

**Comment by lorezyra** [comment]
Content and logos added.

Could you rearrange the company logos to look nicer?

**Comment by Asem-prg** [comment]
> Content and logos added.
> 
> Could you rearrange the company logos to look nicer?

Okay.

You will have it.

**Comment by lorezyra** [comment]
## TIMELINE

- [ ] Make the hover area bigger for the hidden content
- [ ] Change the cursor to pointer for the circle points
- [ ] When user hover/focus on the company name: display the hidden description

**Comment by Asem-prg** [comment]
Apologize for the lack of significant progress last two days, I have been searching for a great "Slider" library for more than a day to use it in "Projects" section.

**Comment by lorezyra** [comment]
> Apologize for the lack of significant progress last two days, I have been searching for a great "Slider" library for more than a day to use it in "Projects" section.

I don't see the need for sliders here. We can completely change the card design for mobile. On the desktop, I don't want to create a new page (at this point). Simply flip the card to the backside and show more details about the project. At a later point, I may create new project pages. For now, it's good enough to display the card with animation for selection and details (on back of card).

**Comment by lorezyra** [comment]
Please drop (remove) the sliders feature on the work page. Let's use responsive design to change the card designs to function on both PC and mobile. The sliders UX is horrible on iPhone. 

For mobile cards, we should use something similar to this:
https://xd.adobe.com/view/5acb3b52-afbf-44d8-a34e-65355325e001-0f98/
_NOTE: This is not the final design._

**Comment by Asem-prg** [comment]
> > Apologize for the lack of significant progress last two days, I have been searching for a great "Slider" library for more than a day to use it in "Projects" section.
> 
> I don't see the need for sliders here. We can completely change the card design for mobile. On the desktop, I don't want to create a new page (at this point). Simply flip the card to the backside and show more details about the project. At a later point, I may create new project pages. For now, it's good enough to display the card with animation for selection and details (on back of card).

Sure.

How to do you find these cards' style

[card.zip](https://github.com/lorezyra/Richie2.com/files/6725168/card.zip)

**Comment by Asem-prg** [comment]
> Please drop (remove) the sliders feature on the work page. Let's use responsive design to change the card designs to function on both PC and mobile. The sliders UX is horrible on iPhone.
> 
> For mobile cards, we should use something similar to this:
> https://xd.adobe.com/view/5acb3b52-afbf-44d8-a34e-65355325e001-0f98/
> _NOTE: This is not the final design._

Slider have been removed, will look for a mobile card design

**Comment by Asem-prg** [comment]
I also liked the hove effect of these cards

[card.zip](https://github.com/lorezyra/Richie2.com/files/6725260/card.zip)

**Comment by lorezyra** [comment]
Not looking for the tilt feature for work page. Maybe we can use on blog.

Please review my comments on : https://github.com/lorezyra/Richie2.com/issues/5#issuecomment-867276546

**Comment by Asem-prg** [comment]
> Not looking for the tilt feature for work page. Maybe we can use on blog. For main site, I wish to minimize the use of Javascript in favor of CSS.
> 
> Please review my comments on : [#5 (comment)](https://github.com/lorezyra/Richie2.com/issues/5#issuecomment-867276546)
> 
> Also, please review my comment for the timeline: [#5 (comment)](https://github.com/lorezyra/Richie2.com/issues/5#issuecomment-867276546)

Yes, I understood you very well. But I was looking for ways to make the cards look even better, but you're reason that you wish to minimize the use of JavaScript in favor of CSS is very good.

I will make the flipping card now.

**Comment by Asem-prg** [comment]
Could please tell me about the reason that's made you change the value of "display" property into "block" value instead of "flex" value?
However it is not clearly shown in "Desktop" screens, it breaks the Navbar layout in mobile screen.

![image](https://user-images.githubusercontent.com/68165112/123668089-70b12c80-d843-11eb-927b-017993409338.png)

and

![Screenshot_20210628-184535](https://user-images.githubusercontent.com/68165112/123668624-f46b1900-d843-11eb-9ddc-ed1c432d43d3.png)

The logo goes up to the top of the Navbar

**Comment by lorezyra** [comment]
Work Page is looking good. However, could you make sure to test the page on Safari? You may need to borrow an iPhone with WiFi enabled to reach your PC to preview the web design. 

The flip on Safari does not seem to work. Look good on Chrome, however.

**Comment by Asem-prg** [comment]
> Work Page is looking good. However, could you make sure to test the page on Safari? You may need to borrow an iPhone with WiFi enabled to reach your PC to preview the web design.
> 
> The flip on Safari does not seem to work. Look good on Chrome, however.
> 
> Also, place a "back" button at the bottom of the card-back. It would be good to allow the user to select text from the card-back. Don't simply flip back to the front on a click. You can probably use a checkbox label for this.

Sure.

But for testing the page on safari browser, I am in progress to download a macOS to install it as VM. It's size is a little bit big so that it will take some time to download.

Rather than wasting time while waiting the OS to be downloaded, I will move to the next issue for now then I will be back to this issue after I install the macOS.

**Comment by lorezyra** [comment]
This looks great!
