### ISSUE TITLE
Mobile Hero missing

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#50]
- On iPhone, the Hero is missing-in-action. 
![IMG_9283](https://user-images.githubusercontent.com/1673222/121108772-4ae8c700-c845-11eb-9fd4-021fa093fbde.PNG)
- We need to move the ```Start Your Journey``` up and reduce the font-size a bit.

**Comment by Asem-prg** [comment]
For now I am using external files to design the page, but after finishing the design I will convert the photos to base64.

**Comment by lorezyra** [comment]
See note in https://github.com/lorezyra/Richie2.com/issues/51#issuecomment-857285290

**Comment by lorezyra** [comment]
Fixed in https://github.com/lorezyra/Richie2.com/commit/a0e6c9d03e4ce200e952e106c72001ddda4bf1b5
