### ISSUE TITLE
Media Queries and viewports

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#58]
- [x] Let's update all our media queries to include not only iPhones
- [x]  in Portrait mode, 
- [x] but landscape too.

##  Devices
- [x] iPhone 12 Mini
```CSS
/* 2340x1080 pixels at 476ppi */
@media only screen 
    and (device-width: 375px) 
    and (device-height: 812px) 
    and (-webkit-device-pixel-ratio: 3) { }
```
This media query is for: iPhone 12 Mini, iPhone 11 Pro, iPhone Xs, and iPhone X

- [x] iPhone 12 and iPhone 12 Pro
```CSS
/* 2532x1170 pixels at 460ppi */
@media only screen 
    and (device-width: 390px) 
    and (device-height: 844px) 
    and (-webkit-device-pixel-ratio: 3) { }
```
This media query is for: iPhone 12 and iPhone 12 Pro

- [x] iPhone 12 Pro Max
```CSS
/* 2778x1284 pixels at 458ppi */
@media only screen 
    and (device-width: 428px) 
    and (device-height: 926px) 
    and (-webkit-device-pixel-ratio: 3) { }
```

- [x] iPhone 11
```CSS
/* 1792x828px at 326ppi */
@media only screen 
    and (device-width: 414px) 
    and (device-height: 896px) 
    and (-webkit-device-pixel-ratio: 2) { }
```
This media query is for: iPhone 11 and iPhone XR

- [x] iPhone 11 Pro
```CSS
/* 2436x1125px at 458ppi */
@media only screen 
    and (device-width: 375px) 
    and (device-height: 812px) 
    and (-webkit-device-pixel-ratio: 3) { }
```
This media query is for: iPhone 12 Mini, iPhone 11 Pro, iPhone Xs, and iPhone X

- [x] iPhone 11 Pro Max
```CSS
/* 2688x1242px at 458ppi */
@media only screen 
    and (device-width: 414px) 
    and (device-height: 896px) 
    and (-webkit-device-pixel-ratio: 3) { }
```
This media query is for: iPhone 11 Pro Max and iPhone Xs Max

## Device orientation
To add landscape or portrait orientation, use the following code:

For portrait:
```CSS
and (orientation : portrait) 
```
For landscape:
```CSS
and (orientation : landscape) 
```

---
[1] https://stackoverflow.com/questions/58087446/all-media-queries-for-iphone-12-pro-max-mini-and-older-iphones

**Comment by Asem-prg** [comment]
The Website looks comfortable in all devices in "Portrait mode" including iPhone devices. So that I will not use the queries for "Portrait mode", I will work on "Landscape mode"

**Comment by lorezyra** [comment]
Looks GREAT!
