### ISSUE TITLE
Update theme on LEGAL/* pages

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#59]
- [x] Update the theme on the legal pages to match the rest of the site.
- [x] Add a Table of Contents that helps the user navigate all legal pages.

**Comment by lorezyra** [comment]
Can we fix the link colors so they look good for both Night & Day themes?

**Comment by lorezyra** [comment]
- [ ] For PC view, the ToC should always be visible. 
- [ ] For small screens, we can limit the ToC to simply the main pages across the top (like on the play page).

**Comment by lorezyra** [comment]
ToC in Night mode has hard to read section (headers). In Day mode, it looks good, but in night mode, the black text should change to white.

**Comment by lorezyra** [comment]
Remember to test (#70) in Night-mode too. The section texts are too dark to read. Contrast is too low.
![image](https://user-images.githubusercontent.com/1673222/126425249-6c102925-4faf-4ac1-9338-c6c60e2dd135.png)

**Comment by Asem-prg** [comment]
The problem fixed.

**Comment by lorezyra** [comment]
This looks good.
