### ISSUE TITLE
Mobile Social menu

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#61]
On iPhone, the social buttons look great! However, it appears that the Safari navigation buttons (at bottom of screen) prevent tapping anything on the bottom 35px or so.

![IMG_9297](https://user-images.githubusercontent.com/1673222/121657748-a207c980-cadb-11eb-878b-a15488746f56.jpeg)

- Can we move the social buttons up 35px just for the iPhones?

Not sure if this is a problem on android phones. If not, then we can keep it at the bottom for Android phones.

**Comment by Asem-prg** [comment]
> On iPhone, the social buttons look great! However, it appears that the Safari navigation buttons (at bottom of screen) prevent tapping anything on the bottom 35px or so.
> 
> ![IMG_9297](https://user-images.githubusercontent.com/1673222/121657748-a207c980-cadb-11eb-878b-a15488746f56.jpeg)
> 
> * Can we move the social buttons up 35px just for the iPhones?
> 
> Not sure if this is a problem on android phones. If not, then we can keep it at the bottom for Android phones.

Some navigation buttons in Android browsers seems to have the same problem.

Fixed.

**Comment by lorezyra** [comment]
Looking good!
