### ISSUE TITLE
Add support for "reduced motion"

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#65]
- Add CSS support for ```reduced motion``` on smartPhones and iPads.

See: 
* https://css-tricks.com/introduction-reduced-motion-media-query/
* https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion
* https://css-tricks.com/dark-modes-with-css/

- Specifically, transitions / transforms or animation should honor this user preference by virtually eliminating the transition times.

**Comment by lorezyra** [comment]
Recommend moving the new CSS to a separate SCSS file.
https://github.com/lorezyra/Richie2.com/blob/584b5b5f20896c55d2a1a04066742b4227fe3b45/assets/scss/reset.scss#L81-L85
Remember that CSS written at the bottom overwrites the rules above it. In other words, the highest priority rules are at the bottom of the CSS set. In this case, you have animation defined below the reset. So, any animation will still take place.

You can load a `userPref.scss` at the bottom of the <page>.scss before compiling.

**Comment by Asem-prg** [comment]
> Recommend moving the new CSS to a separate SCSS file.
> https://github.com/lorezyra/Richie2.com/blob/584b5b5f20896c55d2a1a04066742b4227fe3b45/assets/scss/reset.scss#L81-L85
> 
> 
> Remember that CSS written at the bottom overwrites the rules above it. In other words, the highest priority rules are at the bottom of the CSS set. In this case, you have animation defined below the reset. So, any animation will still take place.
> You can load a `userPref.scss` at the bottom of the .scss before compiling.

But the CSS property with the word "!important" takes a highest specificity marks even more than "CSS inline style" and overwrites all the other values without "!important" word.

But if you want it to be in separated file, Okay I will do that

**Comment by lorezyra** [comment]
There are other "user prefers" options that I would like to support later. 

For example: https://css-tricks.com/dark-modes-with-css/
