### ISSUE TITLE
Use SCSS to build the CSS

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#66]
SCSS is far easier to see how your CSS affects elements in the DOM. VS Code can compile it to CSS for you with the appropriate extension. SCSS makes it far easier to maintain the code after not looking at it for weeks/months.

If you have already created the SCSS, please upload it to github. Otherwise, consider using [this tool](https://beautifytools.com/css-to-scss-converter.php) to quickly build the SCSS file.

For more info:
* https://youtu.be/TymGwiNMlh0
* https://youtu.be/pGcCWhl6ePQ
* https://dev.to/rahxuls/learning-scss-in-5-minutes-h5h

**Comment by Asem-prg** [comment]
Now I am on this!

**Comment by lorezyra** [comment]
Good to review: https://sass-lang.com/guide

Also, let's break-up the single SCSS file into multiple that are easier to read.
For example, move the custom variables to another file: `variables.scss`
Then move the code for specific pages to a separate file: `about.scss`, `work.scss`, etc.

Then we can import them to the main.scss file...
https://www.w3schools.com/sass/sass_import.php

**Comment by lorezyra** [comment]
You might want to double-check the CSS file that was generated. Seems something was lost in the process as the site doesn't look right. The margins are off and the menu doesn't work on mobile screen.

**Comment by lorezyra** [comment]
- [ ] Still need to fix the mobile menu and theme selector (on mobile).
- [ ] Need to fix the images on about page.
- [ ] Footer is not displaying correctly.

**Comment by lorezyra** [comment]
- [ ] Need to repair the copyright section in the footer again.

**Comment by Asem-prg** [comment]
> * [ ]  Need to repair the copyright section in the footer again.
> * [ ]  Work:Projects cards are broken on mobile view in Safari.

I don't see any problems in all my browsers and it looks so good, But I am in progress of downloading macOS Catalina to install it in my VM then I will fix all bugs in Safari browser.

**Comment by lorezyra** [comment]
Might be easier (and better) to borrow an iPhone and test that way.

**Comment by lorezyra** [comment]
Check the iPhoneX view as well.
![image](https://user-images.githubusercontent.com/1673222/124342204-42de3600-dbfd-11eb-8e60-0503b6c30b95.png)

The Copyright section looks poor. Perhaps better to reduce the font-size for this screen size in portrait mode.

**Comment by lorezyra** [comment]
Cards are working in Safari after I downloaded latest commit. Great job.

**Comment by lorezyra** [comment]
Looks good.
