### ISSUE TITLE
Index.html:  change the PNG files to use inline SVG. 

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#69]
Let's change the PNG files to use inline SVG. This way we can have better control over the vectors and fills (via JS/CSS).

- [x] `/assets/img/TravelingHero.svg`
- [x] (please upload the play.svg file)
- [x] (please upload the work.svg file)

NOTE: this should resolve issue #54 .

**Comment by Asem-prg** [comment]
> Let's change the PNG files to use inline SVG. This way we can have better control over the vectors and fills (via JS/CSS).
> 
> * [ ]  `/assets/img/TravelingHero.svg`
> * [x]  (please upload the play.svg file)
> * [x]  (please upload the work.svg file)
> 
> NOTE: this should resolve issue #54 .

I will find a way to use inline SVG in Hero section.

Because of we have 4 images for Hero section and they are switching according to the hover and screen size. But will find a solution to this problem

**Comment by lorezyra** [comment]
> I will find a way to use inline SVG in Hero section.
> 
> Because of we have 4 images for Hero section and they are switching according to the hover and screen size. But will find a solution to this problem

Don't need four images. For the hero, simply change the fill color on the group `travel_path` "Shadow" in (`/assets/img/TravelingHero.svg`)... SVG is _much_ more flexible than rasterized images. 

We can use just SVG for the home page without issues of scale for larger screens.

**Comment by lorezyra** [comment]
- [ ] Need to fix the disappearing SVG hero for Safari mobile browsers.

**Comment by Asem-prg** [comment]
> * [ ]  Need to fix the disappearing SVG hero for Safari mobile browsers.

Working on that

**Comment by Asem-prg** [comment]
I have test the Hero image in a safari browser and it worked exactly as expected without any problems.

![{E6231688-CFEA-4149-A30C-215B03561D3C} png](https://user-images.githubusercontent.com/68165112/125174454-532e7c00-e1ce-11eb-989d-b0a94c594783.jpg)

I wanted to make sure that the page works fine, so I test it in a real iPhone device.

![IMG-20210710-WA0001](https://user-images.githubusercontent.com/68165112/125174480-7d803980-e1ce-11eb-98a8-7ad387362720.jpg)

**Comment by Asem-prg** [comment]
Try to refresh the page in your safari browser when "Hero image" disappear while you shrink browser's size.

**Comment by lorezyra** [comment]
I'm using Safari Version 14.1.1 (16611.2.7.1.4) and it does not render for mobile sizes. Nor does it appear on my iPhone12 ProMax. Maybe you are missing some CSS that handles iPhone12 ProMax screen sizes???
Also, my iPhone is the latest version of iOS (14.5.1). Same issue on my iPad when in portrait mode. However, it displays fine in landscape mode. **So, this tells me we have a CSS error - not an SVG problem.**

iPhone 12 ProMax (portrait):
![IMG_9787](https://user-images.githubusercontent.com/1673222/125183175-587fdb00-e24f-11eb-8d14-2bfa5ce1024c.jpeg)

iPhone 12 ProMax (landscape):
![IMG_9788](https://user-images.githubusercontent.com/1673222/125183334-c4167800-e250-11eb-8c25-b5947d57c2e7.jpeg)



iPad Pro (portrait):
![IMG_0258](https://user-images.githubusercontent.com/1673222/125183274-3470c980-e250-11eb-989c-023c727aa714.jpeg)


PC with Safari (squeezed to imitate mobile device):
![Screen Shot 2021-07-11 at 13 53 36](https://user-images.githubusercontent.com/1673222/125183203-86fdb600-e24f-11eb-94ae-5aa293705c07.png)

**Comment by lorezyra** [comment]
Problem persist. Except now the "Start Your Journey" text is lower on the screen.
![image](https://user-images.githubusercontent.com/1673222/125302687-23ff4280-e367-11eb-958e-ae0d73a72a92.png)

**Comment by lorezyra** [comment]
At least the flickering is gone. 😉

**Comment by lorezyra** [comment]
I can see the HERO now! 😀 
![image](https://user-images.githubusercontent.com/1673222/125555905-ce9e2da1-7a73-462c-a9b8-afe28bf5d5fb.png)

- [ ] However, it seems a bit too small. Is there no way to make all the SVG images stretch to 75% of the screen width?

**Comment by lorezyra** [comment]
On second thought, this looks good enough.
