### ISSUE TITLE
projects.html

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#7]
Here I will highlight my professional & personal projects

## StartUp Projects
- [x] Linspira
- [x] Zyra.Tech
- [x] Technocracy.Works

## Fun Projects
- [ ] LoreZyra.TV
- [x] LEGO projects from [Rebrickable](https://rebrickable.com/users/LoreZyra/profile/).
- [ ] Building a house: link to blog page

* Good example: https://linusbohman.se/projects

**Comment by lorezyra** [comment]
Let's change the format of the projects page.

- [ ] First, create a `projects` folder and move the projects.html page to `/projects/index.html`
- [ ] For the projects above, update the index.html so the cards will link to a dedicated page for each project.
- [ ] All projects will reside in the `/projects/` folder. 
- [ ] Need a design that highlights the details of the project. (Similar to a news article.)

**Comment by lorezyra** [comment]
Can you confirm the CSS for projects on small screens?
![image](https://user-images.githubusercontent.com/1673222/126275062-70baefde-2d99-47ef-a2e0-5206e20f0296.png)

**Comment by lorezyra** [comment]
@Asem-prg , Can you create CSS for the `<blockquote>` tag on the project pages? I need something that adds quotation marks to both sides while making it obvious the paragraph is a quote.

Something like this:
![image](https://user-images.githubusercontent.com/1673222/126601126-c0dbd279-adca-45fd-96f1-13aca27ab72e.png)

**Comment by lorezyra** [comment]
@Asem-prg
- Please note that Linux (back-end servers) is CASE SENSITIVE!!!
P != p…

This is why the CSS wasn't loading. `Projects.css` filename wasn't found.

**Comment by Asem-prg** [comment]
> @Asem-prg
> 
> * Please note that Linux (back-end servers) is CASE SENSITIVE!!!
>   P != p…
> 
> This is why the CSS wasn't loading. `Projects.css` filename wasn't found.

Oh, that was a bad mistake from me :white_frowning_face:

**Comment by lorezyra** [comment]
For the blockquote, please include the `"` double-quote mark on the left and right sides of the bounding box.
Similar to this:
![image](https://user-images.githubusercontent.com/1673222/126740016-9d278a19-5fe8-4355-985b-c61af6c17e55.png)

**Comment by lorezyra** [comment]
The design of the Project index needs to be very different from the Play page. I liked the design we did for the cards on the Work page. For StartUps, please use the work page card design, but without the flip to back. When user clicks on more-info, it opens the startup's detailed page. This is why I copied the code from the work page (and removed the back of the cards).

Also, I don't need the categories at the top. These categories should be with the "fun" projects as I had moved them previously. Take note that I changed the footer links to show just the fun or just the startups.

**Comment by lorezyra** [comment]
Looks awesome! However, we need to 

- [ ] fix the quote marks so they don't obscure the text. 
- [ ] And the quote position on mobile looks odd. 
- [ ] The font "fantasy" (L143) is an odd choice, can you confirm this is what we should use?
https://github.com/lorezyra/Richie2.com/blob/964583e8f5f4e8e04fda92bf3b134edf445b6487/assets/scss/project.scss#L117-L148

Can you check it out?

![image](https://user-images.githubusercontent.com/1673222/126887696-3097b34a-8489-42c2-b145-ec9bd1d18782.png)

![IMG_03D3E4477E4C-1](https://user-images.githubusercontent.com/1673222/126887847-821150e6-2b9c-4993-a5e9-a2e0f505911b.jpeg)

**Comment by lorezyra** [comment]
https://github.com/lorezyra/Richie2.com/commit/13620235376f743995c6fb4f9bb9f4812cc47981#r53945955

**Comment by lorezyra** [comment]
https://css-tricks.com/quoting-in-html-quotations-citations-and-blockquotes/

https://stackoverflow.com/questions/16325687/make-big-quotes-with-blockquote

**Comment by lorezyra** [comment]
Looks good. As projects don't truly depend on blockquotes, I have created a new issue.
