### ISSUE TITLE
play.html: Change design

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#77]
The layout of the photos is fine. However, I'd like to remove the hover action for full image display.

- [x] Take inspiration from [stock.adobe.com](https://stock.adobe.com/search/images?load_type=search&native_visual_search=&similar_content_id=&is_recent_search=&search_type=usertyped&k=projects)
- [x] When user clicks the image, a full width `<div>` opens below the image to reveal the details.
- [x] Provide a close button within the new `div`.
- [x] if user clicks another image, the old, expanded div is closed and the new one opens. (see Adobe stock page for operation)
- [x] This should work on both PC and mobile.
- [x] don't preload these images in CSS. It takes too long for the page to load.

* List of projects
![Screen Shot 2021-07-18 at 22 54 58](https://user-images.githubusercontent.com/1673222/126070153-ff620544-8352-4e37-bd27-cf921e151c87.png)
* After image click, screen expands below clicked image with more details.
![Screen Shot 2021-07-18 at 22 54 45](https://user-images.githubusercontent.com/1673222/126070162-a137cd76-58d7-4979-aa65-bc23deba8a18.png)

**Comment by lorezyra** [comment]
Original design uses images in the CSS (for hover view) that must be downloaded before the page load is considered complete. Meanwhile, the user will probably leave before it gets half-done...


This is why we should not load all the images in CSS. (Too many and too large.)
![image](https://user-images.githubusercontent.com/1673222/127740711-3ac77033-99d0-420b-b008-53a148df46ba.png)

**Comment by lorezyra** [comment]
- [ ] Can we make the photos bigger?
- [ ] Possible to add a stylish border around the entire preview area?
- [ ] Using JS, could we add an arrow (or something) to indicate this photo opened from the thumbnail above? 
       (Maybe use an idea from folder tabs?)

**Comment by lorezyra** [comment]
Mobile view looks good. However, on desktop: can we make the image (in `longInfo`) larger? We have plenty of real-estate to expand. We could make it 65% the screen width.

**Comment by lorezyra** [comment]
In latest commit, the `X` close button is missing. Can you check?

**Comment by Asem-prg** [comment]
I have measured the space `above` and `below` the details section based on largest photo.

I could make it better using JS, but in case JS is disabled it will be broken. So I made it using CSS with a limited quality.

**Comment by lorezyra** [comment]
Okay. When you consider that the images don't load when Javascript is disabled, I think it's okay to use JS here. Otherwise, the visitor won't see much on this page.

**Comment by lorezyra** [comment]
Looks good!
