### ISSUE TITLE
contact.html

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#79]
- [x] Let's create a new "email" page `/contact.html` 
- [x] I'll provide the vector graphic (from stock.adobe.com)
    - See `/assets/img/emails.svg` for the page graphic.
- [x] build a simple email form (I'll handle the backend parts)
* Name `id=name`
* Phone (optional) `id=phone`
* Email `id=email`
* Your text request `id=desc`

---

NOTE: limits on the length of text for each field:
```javascript
    let name = event.name.substring(0, 128);
    let phone = event.phone.substring(0, 24);
    let email = event.email.substring(0, 320);
    let text = event.desc.substring(0, 2048);
```

If user allows JS, then we need to perform validations on the form data:

- [x] Make sure the name uses only alphanumeric text and space.
- [x] phone should have only [0-9.]\-\+\w\\(\\)\\#
    - 0 through 9
    -  `-`
    -  `+`
    - space
    - `(`
    - `)`
    - `.`
    - `#`
- [x] email should allow alphanumeric, dot `.`, plus `+`, minus `-`, underscore `_`, exclamation mark `!`, & `@`
- [x] All fields should *prohibit* the back-tick (\`)  character, the phrase `eval()`, `script:`, and `javascript:`
- [x] prior to sending, all fields need to be `escaped()` 

---

- [x] POST the form data to `api.RichieBartlett.com/m` in JSON format.

---

- [x] On successful return, redirect user to the `/ThankYou/contact.html` #80  page.
- [x] Success result will be in JSON.

---

- [x] update the `work.html` page to use this for email contact (bottom button).

**Comment by lorezyra** [comment]
See `/assets/img/emails.svg` for the page graphic.

**Comment by lorezyra** [comment]
AWS backend: https://aws.amazon.com/blogs/architecture/create-dynamic-contact-forms-for-s3-static-websites-using-aws-lambda-amazon-api-gateway-and-amazon-ses/

**Comment by lorezyra** [comment]
NOTE: limits on the length of text for each field:
```javascript
    let name = event.name.substring(0, 128);
    let phone = event.phone.substring(0, 24);
    let email = event.email.substring(0, 320);
    let text = event.desc.substring(0, 2048);
```

**Comment by lorezyra** [comment]
Once we have this contact page uploaded, I can submit to AWS to increase my account limits.

**Comment by lorezyra** [comment]
Don't forget to use `/assets/img/emails.svg` for the page graphic.

**Comment by lorezyra** [comment]
@Asem-prg , Can we make the `Send` button pulse when focus or hover?

**Comment by lorezyra** [comment]
Here's an example JavaScript from https://aws.amazon.com/blogs/architecture/create-dynamic-contact-forms-for-s3-static-websites-using-aws-lambda-amazon-api-gateway-and-amazon-ses/


```javascript
function submitToAPI(e) {
       e.preventDefault();
       var URL = "https://abc1234.execute-api.us-east-1.amazonaws.com/01/contact";

            var Namere = /[A-Za-z]{1}[A-Za-z]/;
            if (!Namere.test($("#name-input").val())) {
                         alert ("Name can not less than 2 char");
                return;
            }
            var mobilere = /[0-9]{10}/;
            if (!mobilere.test($("#phone-input").val())) {
                alert ("Please enter valid mobile number");
                return;
            }
            if ($("#email-input").val()=="") {
                alert ("Please enter your email id");
                return;
            }

            var reeamil = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,6})?$/;
            if (!reeamil.test($("#email-input").val())) {
                alert ("Please enter valid email address");
                return;
            }

       var name = $("#name-input").val();
       var phone = $("#phone-input").val();
       var email = $("#email-input").val();
       var desc = $("#description-input").val();
       var data = {
          name : name,
          phone : phone,
          email : email,
          desc : desc
        };

       $.ajax({
         type: "POST",
         url : "https://abc1234.execute-api.us-east-1.amazonaws.com/01/contact",
         dataType: "json",
         crossDomain: "true",
         contentType: "application/json; charset=utf-8",
         data: JSON.stringify(data),

         
         success: function () {
           // clear form and show a success message
           alert("Successfull");
           document.getElementById("contact-form").reset();
       location.reload();
         },
         error: function () {
           // show an error message
           alert("UnSuccessfull");
         }});
     }
```

Don't use this exact script. Obviously, would need to make something similar that fits with the code you already wrote.

**Comment by Asem-prg** [comment]
I was trying along the day to access the "API", but I was always end up with this error message

![{4571AF71-8963-4175-ADF3-97B9D7A91E53} png](https://user-images.githubusercontent.com/68165112/127751899-46392727-2c4f-4369-aef1-a265f5f62aa0.jpg)

**Comment by lorezyra** [comment]
Sorry, I should have opened up the security to allow localhost.

**Comment by lorezyra** [comment]
Can you test from your end? I've pushed the latest code to the server.

**Comment by Asem-prg** [comment]
I tested the form with different languages but I still got the error message.

![image](https://user-images.githubusercontent.com/68165112/127773488-e958580c-dfbb-4f54-836c-955a4e480ee1.png)

However this time the request POSTs to the server correctly, but I got no response.
I tried with different languages.

**Comment by lorezyra** [comment]
Don't use localhost. I've banned that location to prevent hackers from taking advantage of my account.

I see you've sent a dozen emails already:
```
Full Name: Asem Alhaidary 
Phone: 775690990 
Email: asemalhaidary.2001@gmail.com 

Text Body: 

Troubleshooting my API. JSON input works. Direct form submit fails. Need to fix data mapping for this method. 
```

**Comment by lorezyra** [comment]
Could you consider how this contact form is layout for iPhone in landscape mode? 
It looks good in portrait mode, but I think we can do better for landscape.

**Comment by Asem-prg** [comment]
> Don't use localhost. I've banned that location to prevent hackers from taking advantage of my account.
> 
> I see you've sent a dozen emails already:
> 
> ```
> Full Name: Asem Alhaidary 
> Phone: 775690990 
> Email: asemalhaidary.2001@gmail.com 
> 
> Text Body: 
> 
> Troubleshooting my API. JSON input works. Direct form submit fails. Need to fix data mapping for this method. 
> ```
> 
> ```
> Full Name: عاصم الحيدري 
> Phone: +967775690990 
> Email: asemalhaidary.2001@gmail.com 
> 
> Text Body: 
> 
> استكشاف أخطاء API الخاصة بي. يعمل إدخال JSON. فشل إرسال النموذج المباشر. تحتاج إلى إصلاح تعيين البيانات لهذه الطريقة. Troubleshooting my API. JSON input works. Direct form submit fails. Need to fix data mapping for this method. 
> ```

Okay, perfect :thumbsup:

**Comment by lorezyra** [comment]
I've completely rebuilt the API for `api.RichieBartlett.com/m`. Previous version didn't handle security tests well. So, I had to rebuild it. The built-in "protections" that AWS offers are insufficient for my needs. So, I wrote my own. 
Maybe someday, AWS will make it easier to build secured API interfaces easier...


Regarding the layout of the contact page, looks good.
