### ISSUE TITLE
LEGAL.html

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#8]
- Here I will list all the standard disclaimers for users of my site.

- [x] copyrights
- [x] privacy
- [x] ToS (terms of service)
- [x] cookies
- [x] DMCA
- GDPR [ deferred to #16 ]
- CCPA [ deferred to #17 ]

- [x] Could use a nice vector background here for all LEGAL pages
- [x] There should be a ToC (table of contents) that should float for better UX.

**Comment by lorezyra** [comment]
https://www.websitepolicies.com/blog/write-common-legal-policies

**Comment by lorezyra** [comment]
https://www.websitepolicies.com/blog/copyright-notice

**Comment by lorezyra** [comment]
https://www.cookiebot.com/en/cookie-declaration/

https://termly.io/products/

**Comment by lorezyra** [comment]
- Acceptable Use Policy:
https://www.websitepolicies.com/policies/edit/A10O946L

**Comment by lorezyra** [comment]
https://www.cookiebot.com/en/ccpa-compliance/

**Comment by lorezyra** [comment]
Current GDPR law: https://eur-lex.europa.eu/eli/reg/2016/679/oj

Current CCPA law: https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=201720180AB375

**Comment by lorezyra** [comment]
The list is non-exhaustive, but covers the most central points of requirements in the CCPA.


- Feature a Do Not Sell My Personal Information link on their website that users can use to opt-out of third party data sales.
- Provide a notice at or before the point of collection informing the consumer of the categories of personal information that the company collects and for what purpose.
- React to an opt-out request within 15 days by stopping further selling and notifying all parties to whom it has sold the personal information in the previous 90 days.
- Obtain opt-in consent from minors age 13 to 16 before selling their personal information, and opt-in consent by parents or legal guardians from consumers under the age of 13.
- Provide consumers free of charge records of the personal information collected in the past 12 months (including sources, commercial purposes and categories of third parties with whom it has been shared) if a consumer requests disclosure or deletion.
- Respond within 10 days of receiving requests for disclosure or deletion with information on how the request will be processed. Substantive responses must be given to the consumer within 45 days of receiving a verified request.
- Include two steps for a deletion request, whereby the consumer can submit the request and subsequently agree to the personal information to be deleted.
- Only offer financial incentives (e.g. different prices, rates and quality) for goods and services if the differences are reasonably related to the value provided to the business by the consumer's data.
- Refrain from discriminating based on a consumer's choice to exercise their rights to opt-out, request disclosure or deletion.

Businesses must also update their privacy policy to include:

- a description of the rights (opt-out, disclosure, deletion) and how to exercise these rights.
- a list of the categories of personal information that the business collects, sells and discloses, and to update this list every 12 months.
- a toll-free phone number or, if a business operates solely online, a link on the website through which the consumer can exercise their rights.

**Comment by lorezyra** [comment]
Must popup on the index page with explicit details on the LEGAL pages.
![image](https://user-images.githubusercontent.com/1673222/119103691-676bbd80-ba56-11eb-90ea-b81bcd587a82.png)

**Comment by lorezyra** [comment]
Cookies must be declared (on cookie.html page) as demonstrated here: https://www.cookiebot.com/en/cookie-declaration/

![Screen Shot 2021-05-21 at 17 12 43](https://user-images.githubusercontent.com/1673222/119104959-d4cc1e00-ba57-11eb-9e7d-5455f411f3ee.png)

**Comment by lorezyra** [comment]
tos = terms.html
GDRP = gdrp.html (not created yet)
CCPA = ccpa.html (not created yet)
CopyRights = acceptable.html#copyrighted

**Comment by lorezyra** [comment]
Which should I use for the LEGAL pages background?

* Option 1
![image](https://user-images.githubusercontent.com/1673222/126150552-fa706030-bb07-435b-bb7a-1c20168c95d8.png)

* Option 2
![image](https://user-images.githubusercontent.com/1673222/126150615-6410ac23-0c32-49c8-ade8-a50b49249765.png)

* Option 3
![image](https://user-images.githubusercontent.com/1673222/126150672-541bc554-7689-4d87-b218-c88785cd82f2.png)

**Comment by Asem-prg** [comment]
I think option number one have a nice vector image and a good background, but the text is hard to read for the users, it would be better add more contrast for text color.

However option 2, 3 are good, but liked option 1 the most.

**Comment by lorezyra** [comment]
Okay. Find `/assets/img/legal.svg` and use this on the legal pages.

**Comment by lorezyra** [comment]
Please find `/assets/img/legal.svg` and use this on the legal pages as a non-moving background.

**Comment by lorezyra** [comment]
PC view looks good. However, the background on Mobile view is not that great. Can you check it out?

**Comment by lorezyra** [comment]
https://github.com/lorezyra/Richie2.com/commit/6c980002bc3a6715ff79ada2c56711f9e69dcb9a#r53933846

**Comment by lorezyra** [comment]
https://github.com/lorezyra/Richie2.com/commit/6c980002bc3a6715ff79ada2c56711f9e69dcb9a#commitcomment-53958853

**Comment by lorezyra** [comment]
Looking good.
