### ISSUE TITLE
Add support for UserPref: dark mode

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#81]
Similar to #65, we should honor the user preference for "dark mode."

If user has set "dark mode" preference, we should always honor it with the Night theme. They can still manually select the Day theme, but it should remain on the Night theme every time they visit.

In the event they do select the Day theme, set the cookie to expire after 2 hours.
If user doesn't have this setting configured, then we keep the standard 2 weeks.

Logic:
- check if user-pref = dark, if true: force to night-theme
- If no dark-pref, then check for saved cookie and selected theme
- no cookie? check local system time and automatically select theme based on time of day. (set to auto)

See notes:
- https://css-tricks.com/dark-modes-with-css/

**Comment by Asem-prg** [comment]
How dose this media query works?

Dose it check the "data-theme" property in <html> tag, just like our custom variables?

**Comment by lorezyra** [comment]
Remember that JavaScript can access and change CSS like a property... You could probably do something like this:
```javascript
if (window.matchMedia('(prefers-color-scheme)').media !== 'not all') {
  console.log('🎉 Dark mode is supported');
}
```

Except, I would also wrap this in a `try..catch` block to prevent errors from collapsing the function.
If the media value equals `dark` then you know to force the Night theme.

**Comment by lorezyra** [comment]
Okay, I see you added `userColorSchemePref()`:
https://github.com/lorezyra/Richie2.com/blob/01938caff5317eb342431c74ff9969fc27acc9ea/assets/js/main.prod.js#L14-L41

Could we also listen for the user-pref change event?

**Comment by lorezyra** [comment]
See https://github.com/lorezyra/Richie2.com/commit/4a0c738b3721e2c51b52c02fa939f7e0472c5650 refactored `setAutoTheme()` into `setTheme()`

**Comment by lorezyra** [comment]
Only thing remaining is to create an event listener for userPref change.

**Comment by lorezyra** [comment]
Will need to revisit the idea of an active event listener for UserPref change... Added value, while nice, is not significant enough to devote time. Besides, when user moves to next page, the logic reads everything again.
