### ISSUE TITLE
error.html (400, 403, 404, 500, 502, 503, 504)

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#9]
- Need a clever set of error pages complete with cute/cool images to explain what went wrong.
- See great examples here: 
    - https://github.com/404
    - https://github.com/HttpErrorPages/HttpErrorPages
    - https://www.searchenginejournal.com/404-page-examples/211154/
    - https://storyset.com/404-error

![Screen Shot 2021-05-15 at 11 42 36](https://user-images.githubusercontent.com/1673222/118345892-af7c7300-b572-11eb-82a5-221afb993cdd.png)

![Screen Shot 2021-05-15 at 11 46 56](https://user-images.githubusercontent.com/1673222/118345991-58c36900-b573-11eb-8b10-4b333b5b12b0.png)

![image](https://user-images.githubusercontent.com/1673222/118472386-bd352280-b743-11eb-97ed-c177e8f8d88d.png)

![image](https://user-images.githubusercontent.com/1673222/118472515-e2c22c00-b743-11eb-9dc9-c98b22b292e6.png)

![image](https://user-images.githubusercontent.com/1673222/118472904-595f2980-b744-11eb-8e28-34f802327e1b.png)

![image](https://user-images.githubusercontent.com/1673222/118472969-6ed45380-b744-11eb-831a-53643cde477b.png)

- [x] error.html
- [x] 400.html
- [x] 403.html
- [x] 404.html
- [x] 500.html
- [x] 502.html
- [x] 503.html
- [x] 504.html

**Comment by Asem-prg** [comment]
I don't know what I supposed to add in "error.html" file, since I have customized 4XX.html, 5XX.html files.

**Comment by lorezyra** [comment]
For `error.html`, it's a general error page that informs the user that an undocumented error occurred.  Something like https://storyset.com/illustration/404-error-page-not-found-with-people-connecting-a-plug/pana for the graphic, and for the text:
```
Not sure what happened or how you got here, but there was an error.
Check out the other pages from the navigation menu.
Or, go to the _home_ page.
```

**Comment by lorezyra** [comment]
For the text in those SVG graphics, let's use the site text style.
https://github.com/lorezyra/Richie2.com/blob/05641e3622963f8fa8f0c175ba669aa2d1b60a7f/404.html#L550-L601

Change the `style` attribute to:
```css
style="fill:var(--text-color)"
```

**Comment by lorezyra** [comment]
Hmm... I thought the shadow would be nice, but I was mistaken.
Perhaps a 1px stroke around the text edge would be better?

Let's remove the `drop-shadow` in favor of a text-stroke:
```css
    stroke: var(--footer-color);
    stroke-width: 1px;
    stroke-opacity: 0.4;
```

**Comment by Asem-prg** [comment]
> For `error.html`, it's a general error page that informs the user that an undocumented error occurred. Something like https://storyset.com/illustration/404-error-page-not-found-with-people-connecting-a-plug/pana for the graphic, and for the text:
> 
> ```
> Not sure what happened or how you got here, but there was an error.
> Check out the other pages from the navigation menu.
> ```

I shortened the first part of the error message into 'Some Thing Went Wrong' .

**Comment by lorezyra** [comment]
> I shortened the first part of the error message into 'Some Thing Went Wrong' .

Okay. "Something" is a single word.

**Comment by lorezyra** [comment]
All but the 504 page look good. The 3D text does not need any shadow. Let's remove it.

**Comment by Asem-prg** [comment]
> Hmm... I thought the shadow would be nice, but I was mistaken.
> Perhaps a 1px stroke around the text edge would be better?
> 
> Let's remove the `drop-shadow` in favor of a text-stroke:
> 
> ```css
>     stroke: var(--footer-color);
>     stroke-width: 1px;
>     stroke-opacity: 0.4;
> ```

Done

**Comment by lorezyra** [comment]
Awesome!
