### ISSUE TITLE
play.html: links need different color

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#91]
Similar to #59, need the `<a>` links to display in a color that is readable. Some of the descriptions for the photos have links that need to be easy to see.

**Comment by Asem-prg** [comment]
Witch links exactly did you meant, while play.html only contains "Photos" and some "text".

**Comment by lorezyra** [comment]
There are indeed links in the description for some photos... if you did a simple search for `<a`, you would find them...

For example:
https://github.com/lorezyra/Richie2.com/blob/32e64709610bdda821d214560c518c9ebfacc8d3/play.html#L553-L555

https://github.com/lorezyra/Richie2.com/blob/32e64709610bdda821d214560c518c9ebfacc8d3/play.html#L610-L611

https://github.com/lorezyra/Richie2.com/blob/32e64709610bdda821d214560c518c9ebfacc8d3/play.html#L863-L864

There are several more...

**Comment by Asem-prg** [comment]
> There are indeed links in the description for some photos... if you did a simple search for `<a`, you would find them...
> 
> For example:
> https://github.com/lorezyra/Richie2.com/blob/32e64709610bdda821d214560c518c9ebfacc8d3/play.html#L553-L555
> 
> https://github.com/lorezyra/Richie2.com/blob/32e64709610bdda821d214560c518c9ebfacc8d3/play.html#L610-L611
> 
> https://github.com/lorezyra/Richie2.com/blob/32e64709610bdda821d214560c518c9ebfacc8d3/play.html#L863-L864
> 
> There are several more...
> 
> PS: The word you are looking for is "which..." not "witch."

Okay, now I got the idea. When added the new text to play.html page, actually I didn't read it again, So I thought that all the text in "play" page is a normal text without any links.

For the miss spelling word, actually English language it's not my native language, because of that sometimes I miss spell some words and have a little bit of grammar problems, But I am still learning until I have it like a native people. :slightly_smiling_face:

**Comment by lorezyra** [comment]
Can we keep the link colors consistent between all pages? Why would we use a different color on legal from play?

**Comment by lorezyra** [comment]
Looks good. Let's use this for other pages where we don't have buttons (links).
