### ISSUE TITLE
Theme Switch: add "auto"

### ISSUE THREAD

**Issue by lorezyra** [lorezyra/Richie2.com#95]
To make it easier for everyone visiting the site, we should add "auto" (automatic) as an option. No need to add a graphic (unless you want to). We can simply add a radio box above the Night/Day options. However, this will likely require you to adjust the shape of the theme-tray for PC and expand the size in the mobile menu.

Default is always: "auto"
(I previously requested to make "dark" the default...)
Auto will set the theme based on local system time.

This is related to #81 and #45

**Comment by Asem-prg** [comment]
I am Sorry for today, I was so busy in preparing some documents for University, I couldn't make a good progress in resolving issues.

**Comment by lorezyra** [comment]
I guess this is still a work-in-progress?
![image](https://user-images.githubusercontent.com/1673222/128276952-8c1bbd14-065e-4d63-a081-b9f66e108f3f.png)

**Comment by lorezyra** [comment]
Can we make sure that one of the theme options is actually `✓` (checked)? 
- Default should be auto. This can be set in the HTML.
- If there's a cookie, then select the appropriate option.

**Comment by Asem-prg** [comment]
> Can we make sure that one of the theme options is actually `✓` (checked)?
> 
> * Default should be auto. This can be set in the HTML.
> * If there's a cookie, then select the appropriate option.

I prefer to make the default theme is `night` theme and make it checked in the HTML. Auto is not a theme, and it will look strange if JavaScript is disabled

**Comment by lorezyra** [comment]
When I say: make "auto" default, I'm referring to the user experience where JS is enabled. Of course, for the JS disabled user, "Night" should be the default.

**Comment by lorezyra** [comment]
For the auto image, can we add a "lighting" icon over it?
![image](https://user-images.githubusercontent.com/1673222/128616794-16411fec-c18d-4d34-accf-2e95cebc0034.png)

**Comment by lorezyra** [comment]
Changing the radio box appearance is cool.
Can we change the icon for "Auto" to use a lighting symbol instead of the encircled `A`?

**Comment by lorezyra** [comment]
Let's change the SVG for the auto. I have an idea to make it "easier" for the visitor to understand. 
Instead of showing night/day side-by-side on the ThemeTray, let's show a round (analog 24H) clock where the hours between 09:00 ~ 18:00 are 'day' and the other is 'night'. For each side of the clock, include the night/day icons. 

Something similar to this, but with better style:
![image](https://user-images.githubusercontent.com/1673222/128681728-dd05a9b3-4d3f-489b-bc75-3abf9c401a03.png)

**Comment by Asem-prg** [comment]
Nice idea, I liked it

**Comment by lorezyra** [comment]
On the night side of the Analog clock, can we make it dark with white "night" icon? This way user knows it's night.

**Comment by lorezyra** [comment]
Looks awesome! Now we need to apply it to the rest of the pages.

**Comment by Asem-prg** [comment]
Okay

**Comment by lorezyra** [comment]
Sweet
